// <auto-generated />
namespace FootballApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Playerhasbeencreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Playerhasbeencreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271206379_Player has been created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
